### ISSUE TITLE
If user enters wrong password or username,  will get pop-up about -  error transferring.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1739] opened 2018-10-23 04:14 UTC
**Steps to reproduce:**

- Open CC
- While entering username and password, type consciously wrong password or username.

Result:
You will get pop up below.
![screenshot from 2018-10-22 11-13-01](https://user-images.githubusercontent.com/9501291/47334918-7fb2aa80-d6aa-11e8-80c7-5f98555e6aa1.png)

**Comment by Almansherov** [comment] 2018-10-24 09:04
Have tested on Debian, Ubuntu, Windows, and Mac.
The issue is fixed on master

**Comment by Almansherov** [comment] 2018-10-31 11:15
No pop up notification now:

<img width="468" alt="screen shot 2018-10-31 at 5 14 48 pm" src="https://user-images.githubusercontent.com/32430693/47784679-8091af00-dd30-11e8-9537-99286d3e4c5a.png">

**Comment by Almansherov** [comment] 2018-10-31 11:29
Tested on all Ubuntu, macos, debian, and windows.
Fixed in prod.

**Closed by Almansherov** 2018-10-31 11:29 UTC
Labels: fixed in dev
