### ISSUE TITLE
Terminal on Mac opens in collapsed view when accessing container via tray

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/control-center#452] opened 2017-12-11 06:11 UTC
If you try to access container on mac via tray, terminal will open, but it will be in collapsed view and you won't be able to detect that it connected properly.

**Comment by akarasulu** [comment] 2017-12-11 07:39
What is collapsed view can you define it? You mean it is not visible on the desktop but minimized?

**Comment by SEFI2** [comment] 2017-12-11 10:39
@akarasulu Yes, it is minimized. The user is not notified that the terminal was opened.

**Comment by amol4anoff** [comment] 2018-03-17 11:19
Seems it is feature of iMac terminal.

**Comment by Erkin97** [comment] 2018-05-15 08:06
Duplicate of #842

**Closed by Erkin97** 2018-05-15 08:06 UTC
Labels: blocker
