### ISSUE TITLE
Make update variables global

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#804] opened 2018-04-08 16:35 UTC
Implementation of this will solve two bugs:
1) when installation of components from About fails, you can't press again Update/Install buttons
2) close About Dlg while installing component, you can't press again update/install buttons

**Comment by ibragim13kz** [comment] 2018-04-20 10:19
1. Can't reproduce component's failure during installation. 
2. Reproduced. So, wanna notice that after closing "About" window, component (x2go) was installed anyway.

**Comment by amangeldizhusubaliev** [comment] 2018-04-21 10:01
done

**Comment by TerGunter** [comment] 2018-05-04 06:41
Fixed on master

**Comment by amangeldizhusubaliev** [comment] 2018-05-21 11:50
done

**Closed** 2018-05-21 12:14 UTC
Labels: done, enhancement, failed in prod, fixed in dev
